name: dawn_lints
description: This package contains the recommended lints for developing projects with Dawn package.
version: 3.0.0-dev.1
homepage: https://github.com/Hawmex/dawn_lints
repository: https://github.com/Hawmex/dawn_lints
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  lints: ^2.0.0
