name: dawn_lints
description: This package contains the recommended lints for developing projects with Dawn package.
version: 3.1.0
homepage: https://github.com/Hawmex/dawn_lints
repository: https://github.com/Hawmex/dawn_lints
environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  lints: ^2.0.1
