name: dawn_lints
description: This package contains the recommended lints for developing projects with Dawn package.
version: 1.0.2
homepage: https://github.com/Hawmex/dawn_lints
repository: https://github.com/Hawmex/dawn_lints
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  lints: ^1.0.0
