name: dawn_lints
description: The recommended lints for Dawn projects.
version: 1.0.0
homepage: https://github.com/Hawmex/dawn_lints
repository: https://github.com/Hawmex/dawn_lints
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  lints: ^1.0.0
